# Business Case Study - Staff Planning

# Problem Statement

 The insurance approval process, i.e., underwriting is one of the important and time-consuming tasks in an insurance application processing. When you submit your insurance application, the underwriter of the company evaluates it based on the details that you provide using a rule-based or an ML model and decides whether or not to approve your application. An insurance company InsurePlus wants you to help them with finding the optimal number of staff that they need for their insurance application approval process for the calendar year 2021. In the industry, the number of staffs is considered as a continuous variable. This is also called a staff Full-Time Equivalent. For example, if a full-time employee (FTE =1) works for 50 hours a week, 10 hours corresponds to 0.2 FTEs.

- The company operates in three states A, B, and C.
- The company can either handle an application with the staff that they hire or outsource it to a vendor. (Assume that there is no capacity limitation to outsourcing.)
- If they hire staff, he/she can handle 40 insurance applications per month when he/she works 100% of the workdays. However, there are days that he/she will be unavailable to process applications due to training, off days, etc.
- A staff memberâ€™s availability (in percentage) to work on processing the insurance applications for each month is shown in the table given below. As mentioned before, with 100% availability, each member can handle 40 applications.

A special note of practical relevance: In the industry, staff availability is predicted using a time-motion study. But in this case, you have been given fixed numbers for each month. States A and B have a regulatory restriction that the outsourced insurance applications cannot be more than 30% and 40% of the total number of applications for each month, respectively. The objective is to optimise the total cost for the application approval process by distributing the right number of applications between the FTEs and the vendors while meeting the monthly demand for each state at the same time.

## Importing the libraries and reading the dataset

In [1]:
# Importing Libraries 

import pandas as pd
import numpy as np
import math
from pyomo.environ import *

In [2]:
from __future__ import division
from pyomo.opt import SolverFactory

In [3]:
# Reading the data from Excel workbook - Staffing.xlsx

InputData = 'Staffing+Data.xlsx'

#Read the data from Demand Data sheet

Demand = pd.read_excel(InputData,sheet_name='DemandData')

#Read the data from Staff Availability sheet

Availability = pd.read_excel (InputData,sheet_name='StaffAvailability')

#Read the data from Cost sheet

Cost = pd.read_excel (InputData,sheet_name='Cost')

#Max Applications Handled by FTE per month

transcost = pd.read_excel( InputData, sheet_name ='ServiceRate')

In [4]:
#Printing the dataframe Demand

Demand.head()

  State Month  Demand
0     A   Jan    5240
1     A   Feb    4878
2     A   Mar    5942
3     A   Apr    2297
4     A   May    1992

In [5]:
#Printing the dataframe Availability

Availability.head()

  State Month    LB    UB  StaffAvPer
0     A   Jan  0.70  0.90        0.81
1     A   Feb  0.65  0.85        0.76
2     A   Mar  0.70  0.80        0.75
3     A   Apr  0.75  0.85        0.80
4     A   May  0.70  0.85        0.78

In [6]:
#Printing the dataframe Cost

Cost.head()

  State Month  AnnualSalary  MonthlySalary  UnitOutSourceCost
0     A   Jan         60000         5000.0                180
1     A   Feb         60000         5000.0                180
2     A   Mar         60000         5000.0                180
3     A   Apr         60000         5000.0                180
4     A   May         60000         5000.0                180

In [7]:
# Consolidating the three dataframes into single dataframe for further analysis

data=pd.merge(Demand,Availability ,on=['State','Month'])

Staff=pd.merge(data,Cost, on = ['State','Month'])

Staff.head()

,State,Month,Demand,LB,UB,StaffAvPer,AnnualSalary,MonthlySalary,UnitOutSourceCost
0,A,Jan,5240,0.70,0.90,0.81,60000,5000.0,180
1,A,Feb,4878,0.65,0.85,0.76,60000,5000.0,180
2,A,Mar,5942,0.70,0.80,0.75,60000,5000.0,180
3,A,Apr,2297,0.75,0.85,0.80,60000,5000.0,180
4,A,May,1992,0.70,0.85,0.78,60000,5000.0,180

In [8]:
#Checking the Shape of Final dataframe

Staff.shape

(36, 9)

In [9]:
#Checking any null values present in the final dataframe

Staff.isnull().sum()

State                0
Month                0
Demand               0
LB                   0
UB                   0
StaffAvPer           0
AnnualSalary         0
MonthlySalary        0
UnitOutSourceCost    0
dtype: int64

# Question 1

The company wants to know the optimised staffing recommendations for the business case described. 
Write the mathematical model for the deterministic optimisation problem. Define and explain your decision variables, objective function and the constraint. (Hint: Use months of the year as the model timeline).

##  Mathematical formulation / Pyomo components

---

**Sets:** 

The indexes for the given problem are, <br>
- State, $s \in State$
- Month, $m \in Month$

---

**Parameters:** 

- $\text{app_FTE}_{s,m} \text{ - Applications processed by FTE}$ <br>


- $\text{app_outsourced}_{s,m} \text{ - Applications outsourced}$ <br>


- $\text{msalary_FTE}_{s,m} \text{ - Monthly Salary of FTE}$ <br>


- $\text{unitcost_outsourced}_{s,m} \text{ - Unit Cost for outsourcing 1 application}$ <br>


- $\text{staff_avail}_{s,m} \text{ - Average availability of FTE}$ <br>


- $\text{lb}_{s,m} \text{ - Minimum availability of FTE}$ <br>


- $\text{ub}_{s,m} \text{ - Maximum availability of FTE}$ <br>


- $\text{max_app_served} \text{ - Number of insurance applications that can be processed by an FTE in a month when working with 100 percent availability}$ <br>




- $\text{outsourced_restA} \text{ - Maximum Number of insurance applications that can be outsourced in a month for State A}$ <br>


- $\text{outsourced_restB} \text{ - Maximum Number of insurance applications that can be outsourced in a month for State B}$ <br>
                                                                                                             
                                                                                                             
---


**Decision variables:**
                                                                                                             
- Total number of  applications processed by FTE for each state and month combination <br>

 $\text{app_FTE}_{s,m} \,\,\,\,\,\,\, \text{where} \ s \in State, m \in Month $<br>
 
 
- Total number of  applications outsourced for each state and month combination <br>

 $\text{app_outsourced}_{s,m} \,\,\,\,\,\,\, \text{where} \ s \in State, m \in Month $<br>


---

**Objective Function:** <br>

To minimize the total cost of insurance approval process by distributing the right number of applications between FTE and outsourced.



\begin{align}
\textrm{min} (\sum \limits _{s,m} \text{app_FTE}_{s,m}* \text{msalary_FTE}_{s,m} + \sum \limits _{s,m} \text{app_outsourced}_{s,m}* \text{unitcost_outsourced}_{s,m})
\end{align}
where $s \in State$ and $m \in Month$

---

**Constraints:**


- **Demand Constraint** :- Demand of Insurance for each state and month combination


>- $\sum \limits _{s,m} \text{app_FTE}_{s,m}* \text{staff_avail}_{s,m}*\text{max_app_served} == \text{demand} \ \ \ \ \forall  {s \in State, m \in Month}$


- **Staff Availability** :- Staff Availability for best and worst case scenerios.


>- $ \text{staff_avail}_{s,m}  > \text{lb}_{s,m} \ \ \ \ \forall  {s \in State, m \in Month}$

>- $ \text{staff_avail}_{s,m}  < \text{ub}_{s,m} \ \ \ \ \forall  {s \in State, m \in Month}$



- **Outsourcing Regulations** :- Regulatory Regulations on States A & B for outsourcing applications.

>- $ \text{app_outsourced}_{s,m}  < (\text{outsourced_restA}_{s,m}*\text{app_outsourced}_{s,m}) \,\,\,\,\,\,\, \text{where} \ s \in A , m \in Month $

>- $ \text{app_outsourced}_{s,m}  < (\text{outsourced_restB}_{s,m}*\text{app_outsourced}_{s,m}) \,\,\,\,\,\,\, \text{where} \ s \in B , m \in Month $

# Question 2

Code the problem is Python and use any optimization package to solve it. Add comments to your code to explain each step.

## Data pre-processing

In [10]:
# Create the required Python data structures for indexes and parameters

#Extracting States into a list

State = Staff['State'].unique()

# Extracting Months into a list

Month = Staff['Month'].unique()

# No of applications processed when FTE is 100% available

FTE_AppServRate = 40

# Create a Dictionary object Demand with index: 'State' and 'Month' and Value as "Demand" column from the Staff Dataframe

Demand = Staff.set_index(['State','Month'])['Demand'].to_dict()

# Create a Dictionary object FTE_Salary with index: 'State' and 'Month' and Value as "MonthlySalary" column 
#from the Staff Dataframe

FTE_Salary = Staff.set_index(['State','Month'])['MonthlySalary'].to_dict()

# Create a Dictionary object UnitOutSourceCost with index: 'State' and 'Month' and Value as "UnitOutSourceCost" column 
#from the Staff Dataframe

UnitOutSourceCost = Staff.set_index(['State','Month'])['UnitOutSourceCost'].to_dict()

# Create a Dictionary object StaffAvPer with index: 'State' and 'Month' and Value as "StaffAvPer" column 
#from the Staff Dataframe

StaffAvPer = Staff.set_index(['State','Month'])['StaffAvPer'].to_dict()

# Create a Dictionary object StaffAv_LB with index: 'State' and 'Month' and Value as "LB" column 
#from the Staff Dataframe

StaffAv_LB = Staff.set_index(['State','Month'])['LB'].to_dict()

# Create a Dictionary object StaffAv_UB with index: 'State' and 'Month' and Value as "UB" column 
#from the Staff Dataframe

StaffAv_UB = Staff.set_index(['State','Month'])['UB'].to_dict()

#### Expected output:

Create a data frame containing the number of outsourced applications  and the number of FTEs for each state-month combination. You can choose to have extra columns like staff availability, demand etc. in your dataframe apart from the ones mentioned earlier.

In [11]:
# Creating a model instance

model = ConcreteModel()

In [12]:
# Define Pyomo sets and Parameters

model.i = Set(initialize=State.tolist(),doc='States')

model.j = Set(initialize=Month.tolist(),doc='Months')

model.demand = Param(model.i,model.j,initialize = Demand,doc='Demand')

model.sa = Param(model.i,model.j,initialize = StaffAvPer,doc = 'StaffAvPercent')

In [13]:
# Decision variables

model.x = Var(model.i,model.j,doc='No of FTE',domain = NonNegativeReals)

model.y = Var(model.i,model.j,doc='No of Outsource App',domain = NonNegativeIntegers)

In [14]:
# Constraints

# Demand Constraint
def total_demand(m,i,j):
    return (m.x[i,j]*40*m.sa[i,j] + m.y[i,j] == m.demand[i,j])
            
model.total_demand = Constraint(model.i,model.j, rule=total_demand)

# Outsourcing Regulation

model.outsource_demand = ConstraintList()
for j in model.j:
    for i in model.i:
        if i == 'A':
            model.outsource_demand.add(expr = model.y[i,j] <= 0.3*model.demand[i,j])
        elif i == 'B':
            model.outsource_demand.add(expr = model.y[i,j] <= 0.4*model.demand[i,j])

In [15]:
# Objective function

model.value = Objective(expr = sum(sum(model.x[i,j]*FTE_Salary[i,j]
                                       + model.y[i,j]*UnitOutSourceCost[i,j] for i in model.i) for j in model.j), 
                        sense= minimize)

In [16]:
# Invoking the solver

result = SolverFactory('glpk').solve(model)
result.write()

# ==========================================================
# = Solver Results                                         =
# ==========================================================
# ----------------------------------------------------------
#   Problem Information
# ----------------------------------------------------------
Problem:
- Name: unknown
  Lower bound: 17962336.4487699
  Upper bound: 17962336.4487699
  Number of objectives: 1
  Number of constraints: 61
  Number of variables: 73
  Number of nonzeros: 97
  Sense: minimize
# ----------------------------------------------------------
#   Solver Information
# ----------------------------------------------------------
Solver:
- Status: ok
  Termination condition: optimal
  Statistics:
    Branch and bound:
      Number of bounded subproblems: 0
      Number of created subproblems: 0
  Error rc: 0
  Time: 0.05039620399475098
# ----------------------------------------------------------
#   Solution Information
# ----------------------------------------------------------
Solution:
- number of solutions: 0
  number of solutions displayed: 0

In [17]:
#Printing the output of the Model

model.pprint()

8 Set Declarations
    demand_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    i : States
        Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    3 : {'A', 'B', 'C'}
    j : Months
        Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   12 : {'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'}
    outsource_demand_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    sa_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    total_demand_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    y_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}

2 Param Declarations
    demand : Demand
        Size=36, Index=demand_index, Domain=Any, Default=None, Mutable=False
        Key          : Value
        ('A', 'Apr') :  2297
        ('A', 'Aug') :  3371
        ('A', 'Dec') :  5183
        ('A', 'Feb') :  4878
        ('A', 'Jan') :  5240
        ('A', 'Jul') :  5334
        ('A', 'Jun') :  2275
        ('A', 'Mar') :  5942
        ('A', 'May') :  1992
        ('A', 'Nov') :  4284
        ('A', 'Oct') :  3529
        ('A', 'Sep') :  3759
        ('B', 'Apr') :  2338
        ('B', 'Aug') :  2620
        ('B', 'Dec') :  4227
        ('B', 'Feb') :  2628
        ('B', 'Jan') :  4927
        ('B', 'Jul') :  4271
        ('B', 'Jun') :  3147
        ('B', 'Mar') :  2974
        ('B', 'May') :  4020
        ('B', 'Nov') :  3137
        ('B', 'Oct') :  4155
        ('B', 'Sep') :  4517
        ('C', 'Apr') :  2261
        ('C', 'Aug') :  2496
        ('C', 'Dec') :  1998
        ('C', 'Feb') :  1967
        ('C', 'Jan') :  1162
        ('C', 'Jul') :  2489
        ('C', 'Jun') :  1642
        ('C', 'Mar') :  1898
        ('C', 'May') :  2030
        ('C', 'Nov') :   963
        ('C', 'Oct') :  2421
        ('C', 'Sep') :   922
    sa : StaffAvPercent
        Size=36, Index=sa_index, Domain=Any, Default=None, Mutable=False
        Key          : Value
        ('A', 'Apr') :   0.8
        ('A', 'Aug') :  0.76
        ('A', 'Dec') :  0.65
        ('A', 'Feb') :  0.76
        ('A', 'Jan') :  0.81
        ('A', 'Jul') :  0.68
        ('A', 'Jun') :  0.73
        ('A', 'Mar') :  0.75
        ('A', 'May') :  0.78
        ('A', 'Nov') :  0.68
        ('A', 'Oct') :  0.73
        ('A', 'Sep') :  0.81
        ('B', 'Apr') :   0.8
        ('B', 'Aug') :  0.76
        ('B', 'Dec') :  0.65
        ('B', 'Feb') :  0.76
        ('B', 'Jan') :  0.81
        ('B', 'Jul') :  0.68
        ('B', 'Jun') :  0.73
        ('B', 'Mar') :  0.75
        ('B', 'May') :  0.78
        ('B', 'Nov') :  0.68
        ('B', 'Oct') :  0.73
        ('B', 'Sep') :  0.81
        ('C', 'Apr') :   0.8
        ('C', 'Aug') :  0.76
        ('C', 'Dec') :  0.65
        ('C', 'Feb') :  0.76
        ('C', 'Jan') :  0.81
        ('C', 'Jul') :  0.68
        ('C', 'Jun') :  0.73
        ('C', 'Mar') :  0.75
        ('C', 'May') :  0.78
        ('C', 'Nov') :  0.68
        ('C', 'Oct') :  0.73
        ('C', 'Sep') :  0.81

2 Var Declarations
    x : No of FTE
        Size=36, Index=x_index
        Key          : Lower : Value            : Upper : Fixed : Stale : Domain
        ('A', 'Apr') :     0 :         71.78125 :  None : False : False : NonNegativeReals
        ('A', 'Aug') :     0 : 110.888157894737 :  None : False : False : NonNegativeReals
        ('A', 'Dec') :     0 : 139.576923076923 :  None : False : False : NonNegativeReals
        ('A', 'Feb') :     0 : 160.460526315789 :  None : False : False : NonNegativeReals
        ('A', 'Jan') :     0 : 161.728395061728 :  None : False : False : NonNegativeReals
        ('A', 'Jul') :     0 : 137.279411764706 :  None : False : False : NonNegativeReals
        ('A', 'Jun') :     0 : 77.9109589041096 :  None : False : False : NonNegativeReals
        ('A', 'Mar') :     0 : 198.066666666667 :  None : False : False : NonNegativeReals
        ('A', 'May') :     0 : 63.8461538461538 :  None : False : False : NonNegativeReals
        ('A', 'Nov') :     0 : 110.257352941176 :  None : False : False : NonNegativeReals
        ('A', 'Oct') :     0 : 120.856164383562 :  None : False : False : NonNegativeReals
        ('A', 'Sep') :     0 : 116.018518518519 :  None : False : False : NonNegativeReals
        ('B', 'Apr') :     0 :          73.0625 :  None : False : False : NonNegativeReals
        ('B', 'Aug') :     0 : 51.7105263157895 :  None : False : False : NonNegativeReals
        ('B', 'Dec') :     0 : 97.5769230769231 :  None : False : False : NonNegativeReals
        ('B', 'Feb') :     0 :           51.875 :  None : False : False : NonNegativeReals
        ('B', 'Jan') :     0 : 152.067901234568 :  None : False : False : NonNegativeReals
        ('B', 'Jul') :     0 : 94.2279411764706 :  None : False : False : NonNegativeReals
        ('B', 'Jun') :     0 : 64.6917808219178 :  None : False : False : NonNegativeReals
        ('B', 'Mar') :     0 :             59.5 :  None : False : False : NonNegativeReals
        ('B', 'May') :     0 : 128.846153846154 :  None : False : False : NonNegativeReals
        ('B', 'Nov') :     0 : 69.2279411764706 :  None : False : False : NonNegativeReals
        ('B', 'Oct') :     0 : 85.3767123287671 :  None : False : False : NonNegativeReals
        ('B', 'Sep') :     0 : 139.413580246914 :  None : False : False : NonNegativeReals
        ('C', 'Apr') :     0 :         70.65625 :  None : False : False : NonNegativeReals
        ('C', 'Aug') :     0 : 82.1052631578947 :  None : False : False : NonNegativeReals
        ('C', 'Dec') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Feb') :     0 : 64.7039473684211 :  None : False : False : NonNegativeReals
        ('C', 'Jan') :     0 : 35.8641975308642 :  None : False : False : NonNegativeReals
        ('C', 'Jul') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Jun') :     0 : 56.2328767123288 :  None : False : False : NonNegativeReals
        ('C', 'Mar') :     0 : 63.2666666666667 :  None : False : False : NonNegativeReals
        ('C', 'May') :     0 : 65.0641025641026 :  None : False : False : NonNegativeReals
        ('C', 'Nov') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Oct') :     0 : 82.9109589041096 :  None : False : False : NonNegativeReals
        ('C', 'Sep') :     0 : 28.4567901234568 :  None : False : False : NonNegativeReals
    y : No of Outsource App
        Size=36, Index=y_index
        Key          : Lower : Value  : Upper : Fixed : Stale : Domain
        ('A', 'Apr') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Aug') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Dec') :     0 : 1554.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Feb') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Jan') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Jul') :     0 : 1600.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Jun') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Mar') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'May') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Nov') :     0 : 1285.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Oct') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Sep') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Apr') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Aug') :     0 : 1048.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Dec') :     0 : 1690.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Feb') :     0 : 1051.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Jan') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Jul') :     0 : 1708.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Jun') :     0 : 1258.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Mar') :     0 : 1189.0 :  None : False : False : NonNegativeIntegers
        ('B', 'May') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Nov') :     0 : 1254.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Oct') :     0 : 1662.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Sep') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Apr') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Aug') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Dec') :     0 : 1998.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Feb') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Jan') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Jul') :     0 : 2489.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Jun') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Mar') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'May') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Nov') :     0 :  963.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Oct') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Sep') :     0 :    0.0 :  None : False : False : NonNegativeIntegers

1 Objective Declarations
    value : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : minimize : 5000.0*x[A,Jan] + 180*y[A,Jan] + 4583.333333333333*x[B,Jan] + 150*y[B,Jan] + 4416.666666666667*x[C,Jan] + 160*y[C,Jan] + 5000.0*x[A,Feb] + 180*y[A,Feb] + 4583.333333333333*x[B,Feb] + 150*y[B,Feb] + 4416.666666666667*x[C,Feb] + 160*y[C,Feb] + 5000.0*x[A,Mar] + 180*y[A,Mar] + 4583.333333333333*x[B,Mar] + 150*y[B,Mar] + 4416.666666666667*x[C,Mar] + 160*y[C,Mar] + 5000.0*x[A,Apr] + 180*y[A,Apr] + 4583.333333333333*x[B,Apr] + 150*y[B,Apr] + 4416.666666666667*x[C,Apr] + 160*y[C,Apr] + 5000.0*x[A,May] + 180*y[A,May] + 4583.333333333333*x[B,May] + 150*y[B,May] + 4416.666666666667*x[C,May] + 160*y[C,May] + 5000.0*x[A,Jun] + 180*y[A,Jun] + 4583.333333333333*x[B,Jun] + 150*y[B,Jun] + 4416.666666666667*x[C,Jun] + 160*y[C,Jun] + 5000.0*x[A,Jul] + 180*y[A,Jul] + 4583.333333333333*x[B,Jul] + 150*y[B,Jul] + 4416.666666666667*x[C,Jul] + 160*y[C,Jul] + 5000.0*x[A,Aug] + 180*y[A,Aug] + 4583.333333333333*x[B,Aug] + 150*y[B,Aug] + 4416.666666666667*x[C,Aug] + 160*y[C,Aug] + 5000.0*x[A,Sep] + 180*y[A,Sep] + 4583.333333333333*x[B,Sep] + 150*y[B,Sep] + 4416.666666666667*x[C,Sep] + 160*y[C,Sep] + 5000.0*x[A,Oct] + 180*y[A,Oct] + 4583.333333333333*x[B,Oct] + 150*y[B,Oct] + 4416.666666666667*x[C,Oct] + 160*y[C,Oct] + 5000.0*x[A,Nov] + 180*y[A,Nov] + 4583.333333333333*x[B,Nov] + 150*y[B,Nov] + 4416.666666666667*x[C,Nov] + 160*y[C,Nov] + 5000.0*x[A,Dec] + 180*y[A,Dec] + 4583.333333333333*x[B,Dec] + 150*y[B,Dec] + 4416.666666666667*x[C,Dec] + 160*y[C,Dec]

2 Constraint Declarations
    outsource_demand : Size=24, Index=outsource_demand_index, Active=True
        Key : Lower : Body     : Upper              : Active
          1 :  -Inf : y[A,Jan] :             1572.0 :   True
          2 :  -Inf : y[B,Jan] : 1970.8000000000002 :   True
          3 :  -Inf : y[A,Feb] : 1463.3999999999999 :   True
          4 :  -Inf : y[B,Feb] :             1051.2 :   True
          5 :  -Inf : y[A,Mar] :             1782.6 :   True
          6 :  -Inf : y[B,Mar] : 1189.6000000000001 :   True
          7 :  -Inf : y[A,Apr] :              689.1 :   True
          8 :  -Inf : y[B,Apr] :              935.2 :   True
          9 :  -Inf : y[A,May] :              597.6 :   True
         10 :  -Inf : y[B,May] :             1608.0 :   True
         11 :  -Inf : y[A,Jun] :              682.5 :   True
         12 :  -Inf : y[B,Jun] : 1258.8000000000002 :   True
         13 :  -Inf : y[A,Jul] :             1600.2 :   True
         14 :  -Inf : y[B,Jul] :             1708.4 :   True
         15 :  -Inf : y[A,Aug] :             1011.3 :   True
         16 :  -Inf : y[B,Aug] :             1048.0 :   True
         17 :  -Inf : y[A,Sep] :             1127.7 :   True
         18 :  -Inf : y[B,Sep] : 1806.8000000000002 :   True
         19 :  -Inf : y[A,Oct] :             1058.7 :   True
         20 :  -Inf : y[B,Oct] :             1662.0 :   True
         21 :  -Inf : y[A,Nov] :             1285.2 :   True
         22 :  -Inf : y[B,Nov] : 1254.8000000000002 :   True
         23 :  -Inf : y[A,Dec] : 1554.8999999999999 :   True
         24 :  -Inf : y[B,Dec] : 1690.8000000000002 :   True
    total_demand : Size=36, Index=total_demand_index, Active=True
        Key          : Lower  : Body                                   : Upper  : Active
        ('A', 'Apr') : 2297.0 :               32.0*x[A,Apr] + y[A,Apr] : 2297.0 :   True
        ('A', 'Aug') : 3371.0 :               30.4*x[A,Aug] + y[A,Aug] : 3371.0 :   True
        ('A', 'Dec') : 5183.0 :               26.0*x[A,Dec] + y[A,Dec] : 5183.0 :   True
        ('A', 'Feb') : 4878.0 :               30.4*x[A,Feb] + y[A,Feb] : 4878.0 :   True
        ('A', 'Jan') : 5240.0 : 32.400000000000006*x[A,Jan] + y[A,Jan] : 5240.0 :   True
        ('A', 'Jul') : 5334.0 : 27.200000000000003*x[A,Jul] + y[A,Jul] : 5334.0 :   True
        ('A', 'Jun') : 2275.0 :               29.2*x[A,Jun] + y[A,Jun] : 2275.0 :   True
        ('A', 'Mar') : 5942.0 :               30.0*x[A,Mar] + y[A,Mar] : 5942.0 :   True
        ('A', 'May') : 1992.0 : 31.200000000000003*x[A,May] + y[A,May] : 1992.0 :   True
        ('A', 'Nov') : 4284.0 : 27.200000000000003*x[A,Nov] + y[A,Nov] : 4284.0 :   True
        ('A', 'Oct') : 3529.0 :               29.2*x[A,Oct] + y[A,Oct] : 3529.0 :   True
        ('A', 'Sep') : 3759.0 : 32.400000000000006*x[A,Sep] + y[A,Sep] : 3759.0 :   True
        ('B', 'Apr') : 2338.0 :               32.0*x[B,Apr] + y[B,Apr] : 2338.0 :   True
        ('B', 'Aug') : 2620.0 :               30.4*x[B,Aug] + y[B,Aug] : 2620.0 :   True
        ('B', 'Dec') : 4227.0 :               26.0*x[B,Dec] + y[B,Dec] : 4227.0 :   True
        ('B', 'Feb') : 2628.0 :               30.4*x[B,Feb] + y[B,Feb] : 2628.0 :   True
        ('B', 'Jan') : 4927.0 : 32.400000000000006*x[B,Jan] + y[B,Jan] : 4927.0 :   True
        ('B', 'Jul') : 4271.0 : 27.200000000000003*x[B,Jul] + y[B,Jul] : 4271.0 :   True
        ('B', 'Jun') : 3147.0 :               29.2*x[B,Jun] + y[B,Jun] : 3147.0 :   True
        ('B', 'Mar') : 2974.0 :               30.0*x[B,Mar] + y[B,Mar] : 2974.0 :   True
        ('B', 'May') : 4020.0 : 31.200000000000003*x[B,May] + y[B,May] : 4020.0 :   True
        ('B', 'Nov') : 3137.0 : 27.200000000000003*x[B,Nov] + y[B,Nov] : 3137.0 :   True
        ('B', 'Oct') : 4155.0 :               29.2*x[B,Oct] + y[B,Oct] : 4155.0 :   True
        ('B', 'Sep') : 4517.0 : 32.400000000000006*x[B,Sep] + y[B,Sep] : 4517.0 :   True
        ('C', 'Apr') : 2261.0 :               32.0*x[C,Apr] + y[C,Apr] : 2261.0 :   True
        ('C', 'Aug') : 2496.0 :               30.4*x[C,Aug] + y[C,Aug] : 2496.0 :   True
        ('C', 'Dec') : 1998.0 :               26.0*x[C,Dec] + y[C,Dec] : 1998.0 :   True
        ('C', 'Feb') : 1967.0 :               30.4*x[C,Feb] + y[C,Feb] : 1967.0 :   True
        ('C', 'Jan') : 1162.0 : 32.400000000000006*x[C,Jan] + y[C,Jan] : 1162.0 :   True
        ('C', 'Jul') : 2489.0 : 27.200000000000003*x[C,Jul] + y[C,Jul] : 2489.0 :   True
        ('C', 'Jun') : 1642.0 :               29.2*x[C,Jun] + y[C,Jun] : 1642.0 :   True
        ('C', 'Mar') : 1898.0 :               30.0*x[C,Mar] + y[C,Mar] : 1898.0 :   True
        ('C', 'May') : 2030.0 : 31.200000000000003*x[C,May] + y[C,May] : 2030.0 :   True
        ('C', 'Nov') :  963.0 : 27.200000000000003*x[C,Nov] + y[C,Nov] :  963.0 :   True
        ('C', 'Oct') : 2421.0 :               29.2*x[C,Oct] + y[C,Oct] : 2421.0 :   True
        ('C', 'Sep') :  922.0 : 32.400000000000006*x[C,Sep] + y[C,Sep] :  922.0 :   True

15 Declarations: i j demand_index demand sa_index sa x_index x y_index y total_demand_index total_demand outsource_demand_index outsource_demand value

In [18]:
# Print the value of the objective function

optimized_cost = round(model.value()/1000000,2)
optimized_cost

17.96

**`Checkpoint 1:`** Seems like the company has to spend around 17.9 m$ in total for the application approval process.

In [19]:
#Creating an empty list

Output_actual = []

# For every iteration, the code below will create a list containing 9 values - State, Month, No of FTE,Demand,
#No of outsource app,No of FTE processed App,Estimated Cost,percent outsourced app,average cost per application

for i in model.i:
    for j in model.j:
        
        #cost for the application approval process
        no_of_fte=model.x[i,j].value
        demand = model.demand[i, j]
        no_of_outsource_app = model.y[i,j].value
        no_of_FTE_processed_app = model.x[i,j].value*40*model.sa[i,j]
        cost = model.x[i,j].value*FTE_Salary[i,j] + model.y[i,j].value*UnitOutSourceCost[i,j]
        percent_outsourced_app = round((no_of_outsource_app/demand)*100,2)
        avg_cost_per_app = round(cost/demand,2)
        
        Output_actual.append([i, j, no_of_fte,demand, no_of_outsource_app,no_of_FTE_processed_app, cost, 
                              percent_outsourced_app,avg_cost_per_app])
        
print(Output_actual)

[['A', 'Jan', 161.728395061728, 5240, 0.0, 5239.999999999987, 808641.97530864, 0.0, 154.32], ['A', 'Feb', 160.460526315789, 4878, 0.0, 4877.999999999985, 802302.631578945, 0.0, 164.47], ['A', 'Mar', 198.066666666667, 5942, 0.0, 5942.000000000011, 990333.333333335, 0.0, 166.67], ['A', 'Apr', 71.78125, 2297, 0.0, 2297.0, 358906.25, 0.0, 156.25], ['A', 'May', 63.8461538461538, 1992, 0.0, 1991.9999999999986, 319230.76923076896, 0.0, 160.26], ['A', 'Jun', 77.9109589041096, 2275, 0.0, 2275.0000000000005, 389554.794520548, 0.0, 171.23], ['A', 'Jul', 137.279411764706, 5334, 1600.0, 3734.000000000003, 974397.05882353, 30.0, 182.68], ['A', 'Aug', 110.888157894737, 3371, 0.0, 3371.0000000000055, 554440.7894736851, 0.0, 164.47], ['A', 'Sep', 116.018518518519, 3759, 0.0, 3759.000000000016, 580092.592592595, 0.0, 154.32], ['A', 'Oct', 120.856164383562, 3529, 0.0, 3529.0000000000105, 604280.82191781, 0.0, 171.23], ['A', 'Nov', 110.257352941176, 4284, 1285.0, 2998.9999999999873, 782586.76470588, 30.0, 182.68], ['A', 'Dec', 139.576923076923, 5183, 1554.0, 3628.999999999998, 977604.615384615, 29.98, 188.62], ['B', 'Jan', 152.067901234568, 4927, 0.0, 4927.000000000004, 696977.8806584367, 0.0, 141.46], ['B', 'Feb', 51.875, 2628, 1051.0, 1577.0, 395410.4166666666, 39.99, 150.46], ['B', 'Mar', 59.5, 2974, 1189.0, 1785.0, 451058.3333333333, 39.98, 151.67], ['B', 'Apr', 73.0625, 2338, 0.0, 2338.0, 334869.7916666666, 0.0, 143.23], ['B', 'May', 128.846153846154, 4020, 0.0, 4020.0000000000055, 590544.8717948725, 0.0, 146.9], ['B', 'Jun', 64.6917808219178, 3147, 1258.0, 1888.9999999999998, 485203.9954337899, 39.97, 154.18], ['B', 'Jul', 94.2279411764706, 4271, 1708.0, 2563.0000000000005, 688078.0637254901, 39.99, 161.1], ['B', 'Aug', 51.7105263157895, 2620, 1048.0, 1572.000000000001, 394206.57894736854, 40.0, 150.46], ['B', 'Sep', 139.413580246914, 4517, 0.0, 4517.000000000014, 638978.9094650224, 0.0, 141.46], ['B', 'Oct', 85.3767123287671, 4155, 1662.0, 2492.999999999999, 640609.9315068491, 40.0, 154.18], ['B', 'Nov', 69.2279411764706, 3137, 1254.0, 1883.0000000000005, 505394.73039215687, 39.97, 161.11], ['B', 'Dec', 97.5769230769231, 4227, 1690.0, 2537.0000000000005, 700727.5641025642, 39.98, 165.77], ['C', 'Jan', 35.8641975308642, 1162, 0.0, 1162.0000000000002, 158400.2057613169, 0.0, 136.32], ['C', 'Feb', 64.7039473684211, 1967, 0.0, 1967.0000000000014, 285775.76754385984, 0.0, 145.29], ['C', 'Mar', 63.2666666666667, 1898, 0.0, 1898.000000000001, 279427.7777777779, 0.0, 147.22], ['C', 'Apr', 70.65625, 2261, 0.0, 2261.0, 312065.1041666667, 0.0, 138.02], ['C', 'May', 65.0641025641026, 2030, 0.0, 2030.0000000000011, 287366.4529914532, 0.0, 141.56], ['C', 'Jun', 56.2328767123288, 1642, 0.0, 1642.000000000001, 248361.8721461189, 0.0, 151.26], ['C', 'Jul', 0.0, 2489, 2489.0, 0.0, 398240.0, 100.0, 160.0], ['C', 'Aug', 82.1052631578947, 2496, 0.0, 2495.9999999999986, 362631.57894736825, 0.0, 145.29], ['C', 'Sep', 28.4567901234568, 922, 0.0, 922.0000000000005, 125684.15637860086, 0.0, 136.32], ['C', 'Oct', 82.9109589041096, 2421, 0.0, 2421.0000000000005, 366190.06849315076, 0.0, 151.26], ['C', 'Nov', 0.0, 963, 963.0, 0.0, 154080.0, 100.0, 160.0], ['C', 'Dec', 0.0, 1998, 1998.0, 0.0, 319680.0, 100.0, 160.0]]

In [20]:
# Creating dataframe for the results

Output_actual = pd.DataFrame(Output_actual, columns = ['State', 'Month', 'No of FTE',"Demand",'No of Outsource App',
                                                       "No of FTE processed App" , 'Estimated Cost', 'Percent Outsourced App',
                                                       'Average Cost Per Application'])

Output_actual[['Estimated Cost in mn $']] = Output_actual[['Estimated Cost']]/1000000

Output_actual['Demand'] = Output_actual['Demand'].astype(int)

Output_actual['No of Outsource App'] = Output_actual['No of Outsource App'].astype(int)

Output_actual['No of FTE processed App'] = Output_actual['No of FTE processed App'].astype(int)

Output_actual = Output_actual.round({"No of FTE":1, "No of Outsource App":0, "Estimated Cost in mn $":1})

In [21]:
#Printing top 5 Rows of Final dataframe

Output_actual.head()

,State,Month,No of FTE,Demand,No of Outsource App,No of FTE processed App,Estimated Cost,Percent Outsourced App,Average Cost Per Application,Estimated Cost in mn $
0,A,Jan,161.7,5240,0,5239,808641.975309,0.0,154.32,0.8
1,A,Feb,160.5,4878,0,4877,802302.631579,0.0,164.47,0.8
2,A,Mar,198.1,5942,0,5942,990333.333333,0.0,166.67,1.0
3,A,Apr,71.8,2297,0,2297,358906.250000,0.0,156.25,0.4
4,A,May,63.8,1992,0,1991,319230.769231,0.0,160.26,0.3

In [22]:
# Writing the results in to an Excel sheet

with pd.ExcelWriter('Output_Actual_Q2.xlsx') as writer:
    Output_actual.to_excel(writer)

# Question 3

#### Worst-case and best-case analysis based on the staffs' availability.

Assuming that the distribution is the same across all the states,

#### 3.1 Worst case analysis 

- 3.1.1 What is the optimal number of staff members for the worst case?Â 

- 3.1.2 What is the percentage of outsourcing for the worst case?Â 

- 3.1.3 What is the average cost per application for the worst case?


#### 3.2 Best case analysis 

- 3.2.1 What is the optimal number of staff members for the best case?Â 

- 3.2.2 What is the percentage of outsourcing for the best case?Â 

- 3.2.3 What is the average cost per application for the best case?

#### Expected output:

For each of the subtasks (3.1 and 3.2) create a data frame containing the number of outsourced applications and the number of FTEs for each state-month combination. You can choose to have extra columns like staff availability, demand etc. in your dataframe apart from the ones mentioned earlier. Also, print the overall average percentage of outsourced applications and the overall average cost per application.

### 3.1 Worst Case Analysis

#### 3.1.1 Optimal number of staff members

In [23]:
# Creating a model instance

model1 = ConcreteModel()

In [24]:
# Define Pyomo sets and Parameters


model1.i = Set(initialize=State.tolist(),doc='States')

model1.j = Set(initialize=Month.tolist(),doc='Months')

model1.demand = Param(model1.i,model1.j,initialize = Demand,doc='Demand')

model1.sa = Param(model1.i,model1.j,initialize = StaffAv_LB,doc = 'StaffLowerBoundPercent')

In [25]:
# Decision variables

model1.x = Var(model1.i,model1.j,doc='No of FTE',domain = NonNegativeReals)

model1.y = Var(model1.i,model1.j,doc='No of Outsource App',domain = NonNegativeIntegers)

In [26]:
# Constraints

def total_demand(m, i, j):
    return (m.x[i, j] * 40 * m.sa[i, j] + m.y[i, j] == m.demand[i, j])


model1.total_demand = Constraint(model1.i, model1.j, rule=total_demand)

# Outsourcing Regulation

model1.outsource_demand = ConstraintList()
for j in model1.j:
    for i in model1.i:
        if i == 'A':
            model1.outsource_demand.add(expr = model1.y[i,j] <= 0.3*model1.demand[i,j])
        elif i == 'B':
            model1.outsource_demand.add(expr = model1.y[i,j] <= 0.4*model1.demand[i,j])

In [27]:
# Objective function

model1.value = Objective(expr = sum(sum(model1.x[i,j]*FTE_Salary[i,j]
                                        + model1.y[i,j]*UnitOutSourceCost[i,j] for i in model1.i) for j in model1.j),
                         sense= minimize)

In [28]:
# Invoking the solver

result = SolverFactory('glpk').solve(model1)
result.write()

# ==========================================================
# = Solver Results                                         =
# ==========================================================
# ----------------------------------------------------------
#   Problem Information
# ----------------------------------------------------------
Problem:
- Name: unknown
  Lower bound: 19599482.5167888
  Upper bound: 19599482.5167888
  Number of objectives: 1
  Number of constraints: 61
  Number of variables: 73
  Number of nonzeros: 97
  Sense: minimize
# ----------------------------------------------------------
#   Solver Information
# ----------------------------------------------------------
Solver:
- Status: ok
  Termination condition: optimal
  Statistics:
    Branch and bound:
      Number of bounded subproblems: 0
      Number of created subproblems: 0
  Error rc: 0
  Time: 0.049071311950683594
# ----------------------------------------------------------
#   Solution Information
# ----------------------------------------------------------
Solution:
- number of solutions: 0
  number of solutions displayed: 0

In [29]:
# Creating dataframe for the results

model1.pprint()

8 Set Declarations
    demand_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    i : States
        Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    3 : {'A', 'B', 'C'}
    j : Months
        Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   12 : {'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'}
    outsource_demand_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    sa_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    total_demand_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    y_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}

2 Param Declarations
    demand : Demand
        Size=36, Index=demand_index, Domain=Any, Default=None, Mutable=False
        Key          : Value
        ('A', 'Apr') :  2297
        ('A', 'Aug') :  3371
        ('A', 'Dec') :  5183
        ('A', 'Feb') :  4878
        ('A', 'Jan') :  5240
        ('A', 'Jul') :  5334
        ('A', 'Jun') :  2275
        ('A', 'Mar') :  5942
        ('A', 'May') :  1992
        ('A', 'Nov') :  4284
        ('A', 'Oct') :  3529
        ('A', 'Sep') :  3759
        ('B', 'Apr') :  2338
        ('B', 'Aug') :  2620
        ('B', 'Dec') :  4227
        ('B', 'Feb') :  2628
        ('B', 'Jan') :  4927
        ('B', 'Jul') :  4271
        ('B', 'Jun') :  3147
        ('B', 'Mar') :  2974
        ('B', 'May') :  4020
        ('B', 'Nov') :  3137
        ('B', 'Oct') :  4155
        ('B', 'Sep') :  4517
        ('C', 'Apr') :  2261
        ('C', 'Aug') :  2496
        ('C', 'Dec') :  1998
        ('C', 'Feb') :  1967
        ('C', 'Jan') :  1162
        ('C', 'Jul') :  2489
        ('C', 'Jun') :  1642
        ('C', 'Mar') :  1898
        ('C', 'May') :  2030
        ('C', 'Nov') :   963
        ('C', 'Oct') :  2421
        ('C', 'Sep') :   922
    sa : StaffLowerBoundPercent
        Size=36, Index=sa_index, Domain=Any, Default=None, Mutable=False
        Key          : Value
        ('A', 'Apr') :  0.75
        ('A', 'Aug') :  0.65
        ('A', 'Dec') :   0.6
        ('A', 'Feb') :  0.65
        ('A', 'Jan') :   0.7
        ('A', 'Jul') :   0.6
        ('A', 'Jun') :  0.65
        ('A', 'Mar') :   0.7
        ('A', 'May') :   0.7
        ('A', 'Nov') :   0.6
        ('A', 'Oct') :  0.65
        ('A', 'Sep') :   0.7
        ('B', 'Apr') :  0.75
        ('B', 'Aug') :  0.65
        ('B', 'Dec') :   0.6
        ('B', 'Feb') :  0.65
        ('B', 'Jan') :   0.7
        ('B', 'Jul') :   0.6
        ('B', 'Jun') :  0.65
        ('B', 'Mar') :   0.7
        ('B', 'May') :   0.7
        ('B', 'Nov') :   0.6
        ('B', 'Oct') :  0.65
        ('B', 'Sep') :   0.7
        ('C', 'Apr') :  0.75
        ('C', 'Aug') :  0.65
        ('C', 'Dec') :   0.6
        ('C', 'Feb') :  0.65
        ('C', 'Jan') :   0.7
        ('C', 'Jul') :   0.6
        ('C', 'Jun') :  0.65
        ('C', 'Mar') :   0.7
        ('C', 'May') :   0.7
        ('C', 'Nov') :   0.6
        ('C', 'Oct') :  0.65
        ('C', 'Sep') :   0.7

2 Var Declarations
    x : No of FTE
        Size=36, Index=x_index
        Key          : Lower : Value            : Upper : Fixed : Stale : Domain
        ('A', 'Apr') :     0 : 76.5666666666667 :  None : False : False : NonNegativeReals
        ('A', 'Aug') :     0 : 90.7692307692308 :  None : False : False : NonNegativeReals
        ('A', 'Dec') :     0 : 151.208333333333 :  None : False : False : NonNegativeReals
        ('A', 'Feb') :     0 : 131.346153846154 :  None : False : False : NonNegativeReals
        ('A', 'Jan') :     0 : 187.142857142857 :  None : False : False : NonNegativeReals
        ('A', 'Jul') :     0 : 155.583333333333 :  None : False : False : NonNegativeReals
        ('A', 'Jun') :     0 : 61.2692307692308 :  None : False : False : NonNegativeReals
        ('A', 'Mar') :     0 : 212.214285714286 :  None : False : False : NonNegativeReals
        ('A', 'May') :     0 : 71.1428571428571 :  None : False : False : NonNegativeReals
        ('A', 'Nov') :     0 : 124.958333333333 :  None : False : False : NonNegativeReals
        ('A', 'Oct') :     0 : 95.0384615384615 :  None : False : False : NonNegativeReals
        ('A', 'Sep') :     0 :           134.25 :  None : False : False : NonNegativeReals
        ('B', 'Apr') :     0 : 46.7666666666667 :  None : False : False : NonNegativeReals
        ('B', 'Aug') :     0 : 60.4615384615385 :  None : False : False : NonNegativeReals
        ('B', 'Dec') :     0 : 105.708333333333 :  None : False : False : NonNegativeReals
        ('B', 'Feb') :     0 : 60.6538461538462 :  None : False : False : NonNegativeReals
        ('B', 'Jan') :     0 : 105.607142857143 :  None : False : False : NonNegativeReals
        ('B', 'Jul') :     0 : 106.791666666667 :  None : False : False : NonNegativeReals
        ('B', 'Jun') :     0 : 72.6538461538462 :  None : False : False : NonNegativeReals
        ('B', 'Mar') :     0 :            63.75 :  None : False : False : NonNegativeReals
        ('B', 'May') :     0 : 86.1428571428571 :  None : False : False : NonNegativeReals
        ('B', 'Nov') :     0 : 78.4583333333333 :  None : False : False : NonNegativeReals
        ('B', 'Oct') :     0 : 95.8846153846154 :  None : False : False : NonNegativeReals
        ('B', 'Sep') :     0 : 96.8214285714286 :  None : False : False : NonNegativeReals
        ('C', 'Apr') :     0 : 75.3666666666667 :  None : False : False : NonNegativeReals
        ('C', 'Aug') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Dec') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Feb') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Jan') :     0 :             41.5 :  None : False : False : NonNegativeReals
        ('C', 'Jul') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Jun') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Mar') :     0 : 67.7857142857143 :  None : False : False : NonNegativeReals
        ('C', 'May') :     0 :             72.5 :  None : False : False : NonNegativeReals
        ('C', 'Nov') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Oct') :     0 :              0.0 :  None : False : False : NonNegativeReals
        ('C', 'Sep') :     0 : 32.9285714285714 :  None : False : False : NonNegativeReals
    y : No of Outsource App
        Size=36, Index=y_index
        Key          : Lower : Value  : Upper : Fixed : Stale : Domain
        ('A', 'Apr') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Aug') :     0 : 1011.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Dec') :     0 : 1554.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Feb') :     0 : 1463.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Jan') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Jul') :     0 : 1600.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Jun') :     0 :  682.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Mar') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'May') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Nov') :     0 : 1285.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Oct') :     0 : 1058.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Sep') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Apr') :     0 :  935.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Aug') :     0 : 1048.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Dec') :     0 : 1690.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Feb') :     0 : 1051.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Jan') :     0 : 1970.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Jul') :     0 : 1708.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Jun') :     0 : 1258.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Mar') :     0 : 1189.0 :  None : False : False : NonNegativeIntegers
        ('B', 'May') :     0 : 1608.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Nov') :     0 : 1254.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Oct') :     0 : 1662.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Sep') :     0 : 1806.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Apr') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Aug') :     0 : 2496.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Dec') :     0 : 1998.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Feb') :     0 : 1967.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Jan') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Jul') :     0 : 2489.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Jun') :     0 : 1642.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Mar') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'May') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Nov') :     0 :  963.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Oct') :     0 : 2421.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Sep') :     0 :    0.0 :  None : False : False : NonNegativeIntegers

1 Objective Declarations
    value : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : minimize : 5000.0*x[A,Jan] + 180*y[A,Jan] + 4583.333333333333*x[B,Jan] + 150*y[B,Jan] + 4416.666666666667*x[C,Jan] + 160*y[C,Jan] + 5000.0*x[A,Feb] + 180*y[A,Feb] + 4583.333333333333*x[B,Feb] + 150*y[B,Feb] + 4416.666666666667*x[C,Feb] + 160*y[C,Feb] + 5000.0*x[A,Mar] + 180*y[A,Mar] + 4583.333333333333*x[B,Mar] + 150*y[B,Mar] + 4416.666666666667*x[C,Mar] + 160*y[C,Mar] + 5000.0*x[A,Apr] + 180*y[A,Apr] + 4583.333333333333*x[B,Apr] + 150*y[B,Apr] + 4416.666666666667*x[C,Apr] + 160*y[C,Apr] + 5000.0*x[A,May] + 180*y[A,May] + 4583.333333333333*x[B,May] + 150*y[B,May] + 4416.666666666667*x[C,May] + 160*y[C,May] + 5000.0*x[A,Jun] + 180*y[A,Jun] + 4583.333333333333*x[B,Jun] + 150*y[B,Jun] + 4416.666666666667*x[C,Jun] + 160*y[C,Jun] + 5000.0*x[A,Jul] + 180*y[A,Jul] + 4583.333333333333*x[B,Jul] + 150*y[B,Jul] + 4416.666666666667*x[C,Jul] + 160*y[C,Jul] + 5000.0*x[A,Aug] + 180*y[A,Aug] + 4583.333333333333*x[B,Aug] + 150*y[B,Aug] + 4416.666666666667*x[C,Aug] + 160*y[C,Aug] + 5000.0*x[A,Sep] + 180*y[A,Sep] + 4583.333333333333*x[B,Sep] + 150*y[B,Sep] + 4416.666666666667*x[C,Sep] + 160*y[C,Sep] + 5000.0*x[A,Oct] + 180*y[A,Oct] + 4583.333333333333*x[B,Oct] + 150*y[B,Oct] + 4416.666666666667*x[C,Oct] + 160*y[C,Oct] + 5000.0*x[A,Nov] + 180*y[A,Nov] + 4583.333333333333*x[B,Nov] + 150*y[B,Nov] + 4416.666666666667*x[C,Nov] + 160*y[C,Nov] + 5000.0*x[A,Dec] + 180*y[A,Dec] + 4583.333333333333*x[B,Dec] + 150*y[B,Dec] + 4416.666666666667*x[C,Dec] + 160*y[C,Dec]

2 Constraint Declarations
    outsource_demand : Size=24, Index=outsource_demand_index, Active=True
        Key : Lower : Body     : Upper              : Active
          1 :  -Inf : y[A,Jan] :             1572.0 :   True
          2 :  -Inf : y[B,Jan] : 1970.8000000000002 :   True
          3 :  -Inf : y[A,Feb] : 1463.3999999999999 :   True
          4 :  -Inf : y[B,Feb] :             1051.2 :   True
          5 :  -Inf : y[A,Mar] :             1782.6 :   True
          6 :  -Inf : y[B,Mar] : 1189.6000000000001 :   True
          7 :  -Inf : y[A,Apr] :              689.1 :   True
          8 :  -Inf : y[B,Apr] :              935.2 :   True
          9 :  -Inf : y[A,May] :              597.6 :   True
         10 :  -Inf : y[B,May] :             1608.0 :   True
         11 :  -Inf : y[A,Jun] :              682.5 :   True
         12 :  -Inf : y[B,Jun] : 1258.8000000000002 :   True
         13 :  -Inf : y[A,Jul] :             1600.2 :   True
         14 :  -Inf : y[B,Jul] :             1708.4 :   True
         15 :  -Inf : y[A,Aug] :             1011.3 :   True
         16 :  -Inf : y[B,Aug] :             1048.0 :   True
         17 :  -Inf : y[A,Sep] :             1127.7 :   True
         18 :  -Inf : y[B,Sep] : 1806.8000000000002 :   True
         19 :  -Inf : y[A,Oct] :             1058.7 :   True
         20 :  -Inf : y[B,Oct] :             1662.0 :   True
         21 :  -Inf : y[A,Nov] :             1285.2 :   True
         22 :  -Inf : y[B,Nov] : 1254.8000000000002 :   True
         23 :  -Inf : y[A,Dec] : 1554.8999999999999 :   True
         24 :  -Inf : y[B,Dec] : 1690.8000000000002 :   True
    total_demand : Size=36, Index=total_demand_index, Active=True
        Key          : Lower  : Body                     : Upper  : Active
        ('A', 'Apr') : 2297.0 : 30.0*x[A,Apr] + y[A,Apr] : 2297.0 :   True
        ('A', 'Aug') : 3371.0 : 26.0*x[A,Aug] + y[A,Aug] : 3371.0 :   True
        ('A', 'Dec') : 5183.0 : 24.0*x[A,Dec] + y[A,Dec] : 5183.0 :   True
        ('A', 'Feb') : 4878.0 : 26.0*x[A,Feb] + y[A,Feb] : 4878.0 :   True
        ('A', 'Jan') : 5240.0 : 28.0*x[A,Jan] + y[A,Jan] : 5240.0 :   True
        ('A', 'Jul') : 5334.0 : 24.0*x[A,Jul] + y[A,Jul] : 5334.0 :   True
        ('A', 'Jun') : 2275.0 : 26.0*x[A,Jun] + y[A,Jun] : 2275.0 :   True
        ('A', 'Mar') : 5942.0 : 28.0*x[A,Mar] + y[A,Mar] : 5942.0 :   True
        ('A', 'May') : 1992.0 : 28.0*x[A,May] + y[A,May] : 1992.0 :   True
        ('A', 'Nov') : 4284.0 : 24.0*x[A,Nov] + y[A,Nov] : 4284.0 :   True
        ('A', 'Oct') : 3529.0 : 26.0*x[A,Oct] + y[A,Oct] : 3529.0 :   True
        ('A', 'Sep') : 3759.0 : 28.0*x[A,Sep] + y[A,Sep] : 3759.0 :   True
        ('B', 'Apr') : 2338.0 : 30.0*x[B,Apr] + y[B,Apr] : 2338.0 :   True
        ('B', 'Aug') : 2620.0 : 26.0*x[B,Aug] + y[B,Aug] : 2620.0 :   True
        ('B', 'Dec') : 4227.0 : 24.0*x[B,Dec] + y[B,Dec] : 4227.0 :   True
        ('B', 'Feb') : 2628.0 : 26.0*x[B,Feb] + y[B,Feb] : 2628.0 :   True
        ('B', 'Jan') : 4927.0 : 28.0*x[B,Jan] + y[B,Jan] : 4927.0 :   True
        ('B', 'Jul') : 4271.0 : 24.0*x[B,Jul] + y[B,Jul] : 4271.0 :   True
        ('B', 'Jun') : 3147.0 : 26.0*x[B,Jun] + y[B,Jun] : 3147.0 :   True
        ('B', 'Mar') : 2974.0 : 28.0*x[B,Mar] + y[B,Mar] : 2974.0 :   True
        ('B', 'May') : 4020.0 : 28.0*x[B,May] + y[B,May] : 4020.0 :   True
        ('B', 'Nov') : 3137.0 : 24.0*x[B,Nov] + y[B,Nov] : 3137.0 :   True
        ('B', 'Oct') : 4155.0 : 26.0*x[B,Oct] + y[B,Oct] : 4155.0 :   True
        ('B', 'Sep') : 4517.0 : 28.0*x[B,Sep] + y[B,Sep] : 4517.0 :   True
        ('C', 'Apr') : 2261.0 : 30.0*x[C,Apr] + y[C,Apr] : 2261.0 :   True
        ('C', 'Aug') : 2496.0 : 26.0*x[C,Aug] + y[C,Aug] : 2496.0 :   True
        ('C', 'Dec') : 1998.0 : 24.0*x[C,Dec] + y[C,Dec] : 1998.0 :   True
        ('C', 'Feb') : 1967.0 : 26.0*x[C,Feb] + y[C,Feb] : 1967.0 :   True
        ('C', 'Jan') : 1162.0 : 28.0*x[C,Jan] + y[C,Jan] : 1162.0 :   True
        ('C', 'Jul') : 2489.0 : 24.0*x[C,Jul] + y[C,Jul] : 2489.0 :   True
        ('C', 'Jun') : 1642.0 : 26.0*x[C,Jun] + y[C,Jun] : 1642.0 :   True
        ('C', 'Mar') : 1898.0 : 28.0*x[C,Mar] + y[C,Mar] : 1898.0 :   True
        ('C', 'May') : 2030.0 : 28.0*x[C,May] + y[C,May] : 2030.0 :   True
        ('C', 'Nov') :  963.0 : 24.0*x[C,Nov] + y[C,Nov] :  963.0 :   True
        ('C', 'Oct') : 2421.0 : 26.0*x[C,Oct] + y[C,Oct] : 2421.0 :   True
        ('C', 'Sep') :  922.0 : 28.0*x[C,Sep] + y[C,Sep] :  922.0 :   True

15 Declarations: i j demand_index demand sa_index sa x_index x y_index y total_demand_index total_demand outsource_demand_index outsource_demand value

In [30]:
# Print the value of the objective function

optimized_cost_worst = round(model1.value()/1000000,2)
optimized_cost_worst

19.6

**`Checkpoint 2:`** The company has to spend around 19.6 m$ in total for the application approval process if the staffs are working with the minimum availability.

In [31]:
#Creating an empty list
Output_worst = []


# For every iteration, the code below will create a list containing 9 values - State, Month, No of FTE,Demand,
#No of outsource app,No of FTE processed App,Estimated Cost,percent outsourced app,average cost per application

for i in model1.i:
    for j in model1.j:
       
        no_of_fte = model1.x[i, j].value
        demand = model1.demand[i, j]
        no_of_outsource_app = model1.y[i, j].value
        no_of_FTE_processed_app = model1.x[i,j].value*40*model1.sa[i,j]
        cost = model1.x[i, j].value*FTE_Salary[i, j] + model1.y[i, j].value*UnitOutSourceCost[i, j]

        percent_outsourced_app = round((no_of_outsource_app/demand)*100,1)
        avg_cost_per_app = round(cost/demand,1)

        Output_worst.append([i, j, no_of_fte,demand, no_of_outsource_app,no_of_FTE_processed_app, 
                             cost, percent_outsourced_app,avg_cost_per_app])
print(Output_worst)

[['A', 'Jan', 187.142857142857, 5240, 0.0, 5239.999999999995, 935714.285714285, 0.0, 178.6], ['A', 'Feb', 131.346153846154, 4878, 1463.0, 3415.0000000000045, 920070.7692307701, 30.0, 188.6], ['A', 'Mar', 212.214285714286, 5942, 0.0, 5942.000000000008, 1061071.42857143, 0.0, 178.6], ['A', 'Apr', 76.5666666666667, 2297, 0.0, 2297.0000000000014, 382833.33333333355, 0.0, 166.7], ['A', 'May', 71.1428571428571, 1992, 0.0, 1991.9999999999986, 355714.2857142855, 0.0, 178.6], ['A', 'Jun', 61.2692307692308, 2275, 682.0, 1593.0000000000011, 429106.153846154, 30.0, 188.6], ['A', 'Jul', 155.583333333333, 5334, 1600.0, 3733.999999999992, 1065916.666666665, 30.0, 199.8], ['A', 'Aug', 90.7692307692308, 3371, 1011.0, 2360.000000000001, 635826.153846154, 30.0, 188.6], ['A', 'Sep', 134.25, 3759, 0.0, 3758.9999999999995, 671250.0, 0.0, 178.6], ['A', 'Oct', 95.0384615384615, 3529, 1058.0, 2470.999999999999, 665632.3076923075, 30.0, 188.6], ['A', 'Nov', 124.958333333333, 4284, 1285.0, 2998.9999999999923, 856091.666666665, 30.0, 199.8], ['A', 'Dec', 151.208333333333, 5183, 1554.0, 3628.9999999999923, 1035761.666666665, 30.0, 199.8], ['B', 'Jan', 105.607142857143, 4927, 1970.0, 2957.000000000004, 779532.7380952388, 40.0, 158.2], ['B', 'Feb', 60.6538461538462, 2628, 1051.0, 1577.0000000000014, 435646.7948717951, 40.0, 165.8], ['B', 'Mar', 63.75, 2974, 1189.0, 1785.0, 470537.5, 40.0, 158.2], ['B', 'Apr', 46.7666666666667, 2338, 935.0, 1403.0000000000011, 354597.22222222236, 40.0, 151.7], ['B', 'May', 86.1428571428571, 4020, 1608.0, 2411.9999999999986, 636021.4285714284, 40.0, 158.2], ['B', 'Jun', 72.6538461538462, 3147, 1258.0, 1889.0000000000014, 521696.79487179505, 40.0, 165.8], ['B', 'Jul', 106.791666666667, 4271, 1708.0, 2563.0000000000077, 745661.805555557, 40.0, 174.6], ['B', 'Aug', 60.4615384615385, 2620, 1048.0, 1572.000000000001, 434315.3846153848, 40.0, 165.8], ['B', 'Sep', 96.8214285714286, 4517, 1806.0, 2711.0000000000005, 714664.8809523811, 40.0, 158.2], ['B', 'Oct', 95.8846153846154, 4155, 1662.0, 2493.0000000000005, 688771.1538461539, 40.0, 165.8], ['B', 'Nov', 78.4583333333333, 3137, 1254.0, 1882.999999999999, 547700.6944444443, 40.0, 174.6], ['B', 'Dec', 105.708333333333, 4227, 1690.0, 2536.9999999999923, 737996.5277777762, 40.0, 174.6], ['C', 'Jan', 41.5, 1162, 0.0, 1162.0, 183291.6666666667, 0.0, 157.7], ['C', 'Feb', 0.0, 1967, 1967.0, 0.0, 314720.0, 100.0, 160.0], ['C', 'Mar', 67.7857142857143, 1898, 0.0, 1898.0000000000007, 299386.90476190485, 0.0, 157.7], ['C', 'Apr', 75.3666666666667, 2261, 0.0, 2261.000000000001, 332869.4444444446, 0.0, 147.2], ['C', 'May', 72.5, 2030, 0.0, 2029.9999999999998, 320208.3333333334, 0.0, 157.7], ['C', 'Jun', 0.0, 1642, 1642.0, 0.0, 262720.0, 100.0, 160.0], ['C', 'Jul', 0.0, 2489, 2489.0, 0.0, 398240.0, 100.0, 160.0], ['C', 'Aug', 0.0, 2496, 2496.0, 0.0, 399360.0, 100.0, 160.0], ['C', 'Sep', 32.9285714285714, 922, 0.0, 921.9999999999991, 145434.5238095237, 0.0, 157.7], ['C', 'Oct', 0.0, 2421, 2421.0, 0.0, 387360.0, 100.0, 160.0], ['C', 'Nov', 0.0, 963, 963.0, 0.0, 154080.0, 100.0, 160.0], ['C', 'Dec', 0.0, 1998, 1998.0, 0.0, 319680.0, 100.0, 160.0]]

In [32]:
# Creating dataframe for the results

Output_worst = pd.DataFrame(Output_worst, columns = ['State', 'Month', 'No of FTE Worst',"Demand",'No of Outsource App Worst',
                                                     "No of FTE Processed App Worst" , 
                                                     'Estimated Cost Worst', 'Percent Outsourced App Worst', 
                                                     'Average Cost Per Application Worst'])

Output_worst['Estimated Cost in mn $ Worst'] = Output_worst[['Estimated Cost Worst']]/1000000

Output_worst['Demand'] = Output_worst['Demand'].astype(int)

Output_worst['No of Outsource App Worst'] = Output_worst['No of Outsource App Worst'].astype(int)

Output_worst['No of FTE Processed App Worst'] = Output_worst['No of FTE Processed App Worst'].astype(int)

Output_worst = Output_worst.round({"No of FTE Worst":1, "No of Outsource App Worst":0, "Estimated Cost in mn $ Worst":1})

In [33]:
#Printing top 5 Rows of Final dataframe

Output_worst.head()

,State,Month,No of FTE Worst,Demand,No of Outsource App Worst,No of FTE Processed App Worst,Estimated Cost Worst,Percent Outsourced App Worst,Average Cost Per Application Worst,Estimated Cost in mn $ Worst
0,A,Jan,187.1,5240,0,5239,9.357143e+05,0.0,178.6,0.9
1,A,Feb,131.3,4878,1463,3415,9.200708e+05,30.0,188.6,0.9
2,A,Mar,212.2,5942,0,5942,1.061071e+06,0.0,178.6,1.1
3,A,Apr,76.6,2297,0,2297,3.828333e+05,0.0,166.7,0.4
4,A,May,71.1,1992,0,1991,3.557143e+05,0.0,178.6,0.4

In [34]:
#Various Parameters
total_outsourcing =  sum(Output_worst['No of Outsource App Worst'])

total_cost = sum(Output_worst['Estimated Cost Worst'])

optimal_staff_members = round(Output_worst['No of FTE Worst'].mean(),1)

total_demand =  sum(Output_worst['Demand'])

average_cost_per_appln = round(total_cost/total_demand,2)

percent_outsourced_app_total = round((total_outsourcing/total_demand)*100,1)

print("Total Outsourced Application: ", total_outsourcing)

print("Total Demand Application: ", total_demand)

print("Optimal Staff Members : ", optimal_staff_members)

Total Outsourced Application:  39808
Total Demand Application:  113294
Optimal Staff Members :  76.7

#### 3.1.2 Percentage of outsourced applications

In [35]:
# write your code here

print("Total Outsourced Application % is : ", percent_outsourced_app_total)

Total Outsourced Application % is :  35.1

#### 3.1.3 Average cost per application

In [36]:
# write your code here

print("Average Cost per Application: ", average_cost_per_appln)

Average Cost per Application:  173.0

In [37]:
# Writing the results in to an Excel sheet

with pd.ExcelWriter('Output_Worst_Q3.xlsx') as writer:
    Output_worst.to_excel(writer)

### 3.2  Best Case Analysis

#### 3.2.1 Optimal number of staff members

In [38]:
# Creating a model instance

model2 = ConcreteModel()

In [39]:
# Define Pyomo sets and Parameters

model2.i = Set(initialize=State.tolist(),doc='States')

model2.j = Set(initialize=Month.tolist(),doc='Months')

model2.demand = Param(model2.i,model2.j,initialize = Demand,doc='Demand')

model2.sa = Param(model2.i,model2.j,initialize = StaffAv_UB,doc = 'StaffUpperBoundPercent')

In [40]:
# Decision variables

model2.x = Var(model2.i,model2.j,doc='No of FTE',domain = NonNegativeReals)

model2.y = Var(model2.i,model2.j,doc='No of Outsource App',domain = NonNegativeIntegers)

In [41]:
# Constraints

# Demand Constraint

def total_demand(m, i, j):
    return (m.x[i, j] * 40 * m.sa[i, j] + m.y[i, j] == m.demand[i, j])


model2.total_demand = Constraint(model2.i, model2.j, rule=total_demand)

# Outsourcing Regulation

model2.outsource_demand = ConstraintList()
for j in model2.j:
    for i in model2.i:
        if i == 'A':
            model2.outsource_demand.add(expr = model2.y[i,j] <= 0.3*model2.demand[i,j])
        elif i == 'B':
            model2.outsource_demand.add(expr = model2.y[i,j] <= 0.4*model2.demand[i,j])

In [42]:
# Objective function

model2.value = Objective(expr = sum(sum(model2.x[i,j]*FTE_Salary[i,j]+ 
                                        model2.y[i,j]*UnitOutSourceCost[i,j] for i in model2.i) for j in model2.j),
                         sense= minimize)

In [43]:
# Invoking the solver

result = SolverFactory('glpk').solve(model2)
result.write()

# ==========================================================
# = Solver Results                                         =
# ==========================================================
# ----------------------------------------------------------
#   Problem Information
# ----------------------------------------------------------
Problem:
- Name: unknown
  Lower bound: 16527535.6379357
  Upper bound: 16527535.6379357
  Number of objectives: 1
  Number of constraints: 61
  Number of variables: 73
  Number of nonzeros: 97
  Sense: minimize
# ----------------------------------------------------------
#   Solver Information
# ----------------------------------------------------------
Solver:
- Status: ok
  Termination condition: optimal
  Statistics:
    Branch and bound:
      Number of bounded subproblems: 0
      Number of created subproblems: 0
  Error rc: 0
  Time: 0.05011868476867676
# ----------------------------------------------------------
#   Solution Information
# ----------------------------------------------------------
Solution:
- number of solutions: 0
  number of solutions displayed: 0

In [52]:
#Printing the Model

model2.pprint()

8 Set Declarations
    demand_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    i : States
        Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :    3 : {'A', 'B', 'C'}
    j : Months
        Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   12 : {'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'}
    outsource_demand_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    sa_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    total_demand_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    x_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}
    y_index : Size=1, Index=None, Ordered=True
        Key  : Dimen : Domain : Size : Members
        None :     2 :    i*j :   36 : {('A', 'Jan'), ('A', 'Feb'), ('A', 'Mar'), ('A', 'Apr'), ('A', 'May'), ('A', 'Jun'), ('A', 'Jul'), ('A', 'Aug'), ('A', 'Sep'), ('A', 'Oct'), ('A', 'Nov'), ('A', 'Dec'), ('B', 'Jan'), ('B', 'Feb'), ('B', 'Mar'), ('B', 'Apr'), ('B', 'May'), ('B', 'Jun'), ('B', 'Jul'), ('B', 'Aug'), ('B', 'Sep'), ('B', 'Oct'), ('B', 'Nov'), ('B', 'Dec'), ('C', 'Jan'), ('C', 'Feb'), ('C', 'Mar'), ('C', 'Apr'), ('C', 'May'), ('C', 'Jun'), ('C', 'Jul'), ('C', 'Aug'), ('C', 'Sep'), ('C', 'Oct'), ('C', 'Nov'), ('C', 'Dec')}

2 Param Declarations
    demand : Demand
        Size=36, Index=demand_index, Domain=Any, Default=None, Mutable=False
        Key          : Value
        ('A', 'Apr') :  2297
        ('A', 'Aug') :  3371
        ('A', 'Dec') :  5183
        ('A', 'Feb') :  4878
        ('A', 'Jan') :  5240
        ('A', 'Jul') :  5334
        ('A', 'Jun') :  2275
        ('A', 'Mar') :  5942
        ('A', 'May') :  1992
        ('A', 'Nov') :  4284
        ('A', 'Oct') :  3529
        ('A', 'Sep') :  3759
        ('B', 'Apr') :  2338
        ('B', 'Aug') :  2620
        ('B', 'Dec') :  4227
        ('B', 'Feb') :  2628
        ('B', 'Jan') :  4927
        ('B', 'Jul') :  4271
        ('B', 'Jun') :  3147
        ('B', 'Mar') :  2974
        ('B', 'May') :  4020
        ('B', 'Nov') :  3137
        ('B', 'Oct') :  4155
        ('B', 'Sep') :  4517
        ('C', 'Apr') :  2261
        ('C', 'Aug') :  2496
        ('C', 'Dec') :  1998
        ('C', 'Feb') :  1967
        ('C', 'Jan') :  1162
        ('C', 'Jul') :  2489
        ('C', 'Jun') :  1642
        ('C', 'Mar') :  1898
        ('C', 'May') :  2030
        ('C', 'Nov') :   963
        ('C', 'Oct') :  2421
        ('C', 'Sep') :   922
    sa : StaffUpperBoundPercent
        Size=36, Index=sa_index, Domain=Any, Default=None, Mutable=False
        Key          : Value
        ('A', 'Apr') :  0.85
        ('A', 'Aug') :  0.85
        ('A', 'Dec') :   0.7
        ('A', 'Feb') :  0.85
        ('A', 'Jan') :   0.9
        ('A', 'Jul') :  0.75
        ('A', 'Jun') :   0.8
        ('A', 'Mar') :   0.8
        ('A', 'May') :  0.85
        ('A', 'Nov') :  0.75
        ('A', 'Oct') :   0.8
        ('A', 'Sep') :   0.9
        ('B', 'Apr') :  0.85
        ('B', 'Aug') :  0.85
        ('B', 'Dec') :   0.7
        ('B', 'Feb') :  0.85
        ('B', 'Jan') :   0.9
        ('B', 'Jul') :  0.75
        ('B', 'Jun') :   0.8
        ('B', 'Mar') :   0.8
        ('B', 'May') :  0.85
        ('B', 'Nov') :  0.75
        ('B', 'Oct') :   0.8
        ('B', 'Sep') :   0.9
        ('C', 'Apr') :  0.85
        ('C', 'Aug') :  0.85
        ('C', 'Dec') :   0.7
        ('C', 'Feb') :  0.85
        ('C', 'Jan') :   0.9
        ('C', 'Jul') :  0.75
        ('C', 'Jun') :   0.8
        ('C', 'Mar') :   0.8
        ('C', 'May') :  0.85
        ('C', 'Nov') :  0.75
        ('C', 'Oct') :   0.8
        ('C', 'Sep') :   0.9

2 Var Declarations
    x : No of FTE
        Size=36, Index=x_index
        Key          : Lower : Value            : Upper : Fixed : Stale : Domain
        ('A', 'Apr') :     0 : 67.5588235294118 :  None : False : False : NonNegativeReals
        ('A', 'Aug') :     0 : 99.1470588235294 :  None : False : False : NonNegativeReals
        ('A', 'Dec') :     0 : 185.107142857143 :  None : False : False : NonNegativeReals
        ('A', 'Feb') :     0 : 143.470588235294 :  None : False : False : NonNegativeReals
        ('A', 'Jan') :     0 : 145.555555555556 :  None : False : False : NonNegativeReals
        ('A', 'Jul') :     0 :            177.8 :  None : False : False : NonNegativeReals
        ('A', 'Jun') :     0 :         71.09375 :  None : False : False : NonNegativeReals
        ('A', 'Mar') :     0 :         185.6875 :  None : False : False : NonNegativeReals
        ('A', 'May') :     0 : 58.5882352941176 :  None : False : False : NonNegativeReals
        ('A', 'Nov') :     0 :            142.8 :  None : False : False : NonNegativeReals
        ('A', 'Oct') :     0 :        110.28125 :  None : False : False : NonNegativeReals
        ('A', 'Sep') :     0 : 104.416666666667 :  None : False : False : NonNegativeReals
        ('B', 'Apr') :     0 : 68.7647058823529 :  None : False : False : NonNegativeReals
        ('B', 'Aug') :     0 : 77.0588235294118 :  None : False : False : NonNegativeReals
        ('B', 'Dec') :     0 : 90.6071428571429 :  None : False : False : NonNegativeReals
        ('B', 'Feb') :     0 : 77.2941176470588 :  None : False : False : NonNegativeReals
        ('B', 'Jan') :     0 : 136.861111111111 :  None : False : False : NonNegativeReals
        ('B', 'Jul') :     0 : 85.4333333333333 :  None : False : False : NonNegativeReals
        ('B', 'Jun') :     0 :         98.34375 :  None : False : False : NonNegativeReals
        ('B', 'Mar') :     0 :          92.9375 :  None : False : False : NonNegativeReals
        ('B', 'May') :     0 : 118.235294117647 :  None : False : False : NonNegativeReals
        ('B', 'Nov') :     0 : 62.7666666666667 :  None : False : False : NonNegativeReals
        ('B', 'Oct') :     0 :        129.84375 :  None : False : False : NonNegativeReals
        ('B', 'Sep') :     0 : 125.472222222222 :  None : False : False : NonNegativeReals
        ('C', 'Apr') :     0 :             66.5 :  None : False : False : NonNegativeReals
        ('C', 'Aug') :     0 : 73.4117647058823 :  None : False : False : NonNegativeReals
        ('C', 'Dec') :     0 : 71.3571428571429 :  None : False : False : NonNegativeReals
        ('C', 'Feb') :     0 : 57.8529411764706 :  None : False : False : NonNegativeReals
        ('C', 'Jan') :     0 : 32.2777777777778 :  None : False : False : NonNegativeReals
        ('C', 'Jul') :     0 : 82.9666666666667 :  None : False : False : NonNegativeReals
        ('C', 'Jun') :     0 :          51.3125 :  None : False : False : NonNegativeReals
        ('C', 'Mar') :     0 :          59.3125 :  None : False : False : NonNegativeReals
        ('C', 'May') :     0 : 59.7058823529412 :  None : False : False : NonNegativeReals
        ('C', 'Nov') :     0 :             32.1 :  None : False : False : NonNegativeReals
        ('C', 'Oct') :     0 :         75.65625 :  None : False : False : NonNegativeReals
        ('C', 'Sep') :     0 : 25.6111111111111 :  None : False : False : NonNegativeReals
    y : No of Outsource App
        Size=36, Index=y_index
        Key          : Lower : Value  : Upper : Fixed : Stale : Domain
        ('A', 'Apr') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Aug') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Dec') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Feb') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Jan') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Jul') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Jun') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Mar') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'May') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Nov') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Oct') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('A', 'Sep') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Apr') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Aug') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Dec') :     0 : 1690.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Feb') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Jan') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Jul') :     0 : 1708.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Jun') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Mar') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'May') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Nov') :     0 : 1254.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Oct') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('B', 'Sep') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Apr') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Aug') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Dec') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Feb') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Jan') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Jul') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Jun') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Mar') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'May') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Nov') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Oct') :     0 :    0.0 :  None : False : False : NonNegativeIntegers
        ('C', 'Sep') :     0 :    0.0 :  None : False : False : NonNegativeIntegers

1 Objective Declarations
    value : Size=1, Index=None, Active=True
        Key  : Active : Sense    : Expression
        None :   True : minimize : 5000.0*x[A,Jan] + 180*y[A,Jan] + 4583.333333333333*x[B,Jan] + 150*y[B,Jan] + 4416.666666666667*x[C,Jan] + 160*y[C,Jan] + 5000.0*x[A,Feb] + 180*y[A,Feb] + 4583.333333333333*x[B,Feb] + 150*y[B,Feb] + 4416.666666666667*x[C,Feb] + 160*y[C,Feb] + 5000.0*x[A,Mar] + 180*y[A,Mar] + 4583.333333333333*x[B,Mar] + 150*y[B,Mar] + 4416.666666666667*x[C,Mar] + 160*y[C,Mar] + 5000.0*x[A,Apr] + 180*y[A,Apr] + 4583.333333333333*x[B,Apr] + 150*y[B,Apr] + 4416.666666666667*x[C,Apr] + 160*y[C,Apr] + 5000.0*x[A,May] + 180*y[A,May] + 4583.333333333333*x[B,May] + 150*y[B,May] + 4416.666666666667*x[C,May] + 160*y[C,May] + 5000.0*x[A,Jun] + 180*y[A,Jun] + 4583.333333333333*x[B,Jun] + 150*y[B,Jun] + 4416.666666666667*x[C,Jun] + 160*y[C,Jun] + 5000.0*x[A,Jul] + 180*y[A,Jul] + 4583.333333333333*x[B,Jul] + 150*y[B,Jul] + 4416.666666666667*x[C,Jul] + 160*y[C,Jul] + 5000.0*x[A,Aug] + 180*y[A,Aug] + 4583.333333333333*x[B,Aug] + 150*y[B,Aug] + 4416.666666666667*x[C,Aug] + 160*y[C,Aug] + 5000.0*x[A,Sep] + 180*y[A,Sep] + 4583.333333333333*x[B,Sep] + 150*y[B,Sep] + 4416.666666666667*x[C,Sep] + 160*y[C,Sep] + 5000.0*x[A,Oct] + 180*y[A,Oct] + 4583.333333333333*x[B,Oct] + 150*y[B,Oct] + 4416.666666666667*x[C,Oct] + 160*y[C,Oct] + 5000.0*x[A,Nov] + 180*y[A,Nov] + 4583.333333333333*x[B,Nov] + 150*y[B,Nov] + 4416.666666666667*x[C,Nov] + 160*y[C,Nov] + 5000.0*x[A,Dec] + 180*y[A,Dec] + 4583.333333333333*x[B,Dec] + 150*y[B,Dec] + 4416.666666666667*x[C,Dec] + 160*y[C,Dec]

2 Constraint Declarations
    outsource_demand : Size=24, Index=outsource_demand_index, Active=True
        Key : Lower : Body     : Upper              : Active
          1 :  -Inf : y[A,Jan] :             1572.0 :   True
          2 :  -Inf : y[B,Jan] : 1970.8000000000002 :   True
          3 :  -Inf : y[A,Feb] : 1463.3999999999999 :   True
          4 :  -Inf : y[B,Feb] :             1051.2 :   True
          5 :  -Inf : y[A,Mar] :             1782.6 :   True
          6 :  -Inf : y[B,Mar] : 1189.6000000000001 :   True
          7 :  -Inf : y[A,Apr] :              689.1 :   True
          8 :  -Inf : y[B,Apr] :              935.2 :   True
          9 :  -Inf : y[A,May] :              597.6 :   True
         10 :  -Inf : y[B,May] :             1608.0 :   True
         11 :  -Inf : y[A,Jun] :              682.5 :   True
         12 :  -Inf : y[B,Jun] : 1258.8000000000002 :   True
         13 :  -Inf : y[A,Jul] :             1600.2 :   True
         14 :  -Inf : y[B,Jul] :             1708.4 :   True
         15 :  -Inf : y[A,Aug] :             1011.3 :   True
         16 :  -Inf : y[B,Aug] :             1048.0 :   True
         17 :  -Inf : y[A,Sep] :             1127.7 :   True
         18 :  -Inf : y[B,Sep] : 1806.8000000000002 :   True
         19 :  -Inf : y[A,Oct] :             1058.7 :   True
         20 :  -Inf : y[B,Oct] :             1662.0 :   True
         21 :  -Inf : y[A,Nov] :             1285.2 :   True
         22 :  -Inf : y[B,Nov] : 1254.8000000000002 :   True
         23 :  -Inf : y[A,Dec] : 1554.8999999999999 :   True
         24 :  -Inf : y[B,Dec] : 1690.8000000000002 :   True
    total_demand : Size=36, Index=total_demand_index, Active=True
        Key          : Lower  : Body                     : Upper  : Active
        ('A', 'Apr') : 2297.0 : 34.0*x[A,Apr] + y[A,Apr] : 2297.0 :   True
        ('A', 'Aug') : 3371.0 : 34.0*x[A,Aug] + y[A,Aug] : 3371.0 :   True
        ('A', 'Dec') : 5183.0 : 28.0*x[A,Dec] + y[A,Dec] : 5183.0 :   True
        ('A', 'Feb') : 4878.0 : 34.0*x[A,Feb] + y[A,Feb] : 4878.0 :   True
        ('A', 'Jan') : 5240.0 : 36.0*x[A,Jan] + y[A,Jan] : 5240.0 :   True
        ('A', 'Jul') : 5334.0 : 30.0*x[A,Jul] + y[A,Jul] : 5334.0 :   True
        ('A', 'Jun') : 2275.0 : 32.0*x[A,Jun] + y[A,Jun] : 2275.0 :   True
        ('A', 'Mar') : 5942.0 : 32.0*x[A,Mar] + y[A,Mar] : 5942.0 :   True
        ('A', 'May') : 1992.0 : 34.0*x[A,May] + y[A,May] : 1992.0 :   True
        ('A', 'Nov') : 4284.0 : 30.0*x[A,Nov] + y[A,Nov] : 4284.0 :   True
        ('A', 'Oct') : 3529.0 : 32.0*x[A,Oct] + y[A,Oct] : 3529.0 :   True
        ('A', 'Sep') : 3759.0 : 36.0*x[A,Sep] + y[A,Sep] : 3759.0 :   True
        ('B', 'Apr') : 2338.0 : 34.0*x[B,Apr] + y[B,Apr] : 2338.0 :   True
        ('B', 'Aug') : 2620.0 : 34.0*x[B,Aug] + y[B,Aug] : 2620.0 :   True
        ('B', 'Dec') : 4227.0 : 28.0*x[B,Dec] + y[B,Dec] : 4227.0 :   True
        ('B', 'Feb') : 2628.0 : 34.0*x[B,Feb] + y[B,Feb] : 2628.0 :   True
        ('B', 'Jan') : 4927.0 : 36.0*x[B,Jan] + y[B,Jan] : 4927.0 :   True
        ('B', 'Jul') : 4271.0 : 30.0*x[B,Jul] + y[B,Jul] : 4271.0 :   True
        ('B', 'Jun') : 3147.0 : 32.0*x[B,Jun] + y[B,Jun] : 3147.0 :   True
        ('B', 'Mar') : 2974.0 : 32.0*x[B,Mar] + y[B,Mar] : 2974.0 :   True
        ('B', 'May') : 4020.0 : 34.0*x[B,May] + y[B,May] : 4020.0 :   True
        ('B', 'Nov') : 3137.0 : 30.0*x[B,Nov] + y[B,Nov] : 3137.0 :   True
        ('B', 'Oct') : 4155.0 : 32.0*x[B,Oct] + y[B,Oct] : 4155.0 :   True
        ('B', 'Sep') : 4517.0 : 36.0*x[B,Sep] + y[B,Sep] : 4517.0 :   True
        ('C', 'Apr') : 2261.0 : 34.0*x[C,Apr] + y[C,Apr] : 2261.0 :   True
        ('C', 'Aug') : 2496.0 : 34.0*x[C,Aug] + y[C,Aug] : 2496.0 :   True
        ('C', 'Dec') : 1998.0 : 28.0*x[C,Dec] + y[C,Dec] : 1998.0 :   True
        ('C', 'Feb') : 1967.0 : 34.0*x[C,Feb] + y[C,Feb] : 1967.0 :   True
        ('C', 'Jan') : 1162.0 : 36.0*x[C,Jan] + y[C,Jan] : 1162.0 :   True
        ('C', 'Jul') : 2489.0 : 30.0*x[C,Jul] + y[C,Jul] : 2489.0 :   True
        ('C', 'Jun') : 1642.0 : 32.0*x[C,Jun] + y[C,Jun] : 1642.0 :   True
        ('C', 'Mar') : 1898.0 : 32.0*x[C,Mar] + y[C,Mar] : 1898.0 :   True
        ('C', 'May') : 2030.0 : 34.0*x[C,May] + y[C,May] : 2030.0 :   True
        ('C', 'Nov') :  963.0 : 30.0*x[C,Nov] + y[C,Nov] :  963.0 :   True
        ('C', 'Oct') : 2421.0 : 32.0*x[C,Oct] + y[C,Oct] : 2421.0 :   True
        ('C', 'Sep') :  922.0 : 36.0*x[C,Sep] + y[C,Sep] :  922.0 :   True

15 Declarations: i j demand_index demand sa_index sa x_index x y_index y total_demand_index total_demand outsource_demand_index outsource_demand value

In [53]:
# Print the value of the objective function

optimized_cost_best = round(model2.value()/1000000,2)
optimized_cost_best

16.53

**`Checkpoint 3:`** The company has to spend around 16.5 m$ in total for the application approval process if the staffs are working with the maximum availability.

In [46]:
#Creating an empty list

Output_best = []

# For every iteration, the code below will create a list containing 9 values - State, Month, No of FTE,Demand,
#No of outsource app,No of FTE processed App,Estimated Cost,percent outsourced app,average cost per application

for i in model2.i:
    for j in model2.j:
        # cost for the application approval process
        no_of_fte = model2.x[i, j].value
        demand = model2.demand[i, j]
        no_of_outsource_app = model2.y[i, j].value
        no_of_FTE_processed_app = model2.x[i,j].value*40*model2.sa[i,j]
        cost = model2.x[i, j].value*FTE_Salary[i, j] + model2.y[i, j].value*UnitOutSourceCost[i, j]

        percent_outsourced_app = round((no_of_outsource_app/demand)*100,1)
        avg_cost_per_app = round(cost/demand,1)

        Output_best.append([i, j, no_of_fte,demand, no_of_outsource_app,no_of_FTE_processed_app, 
                            cost, percent_outsourced_app,avg_cost_per_app])

        print(Output_best)

[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6], ['B', 'Jan', 136.861111111111, 4927, 0.0, 4926.999999999996, 627280.092592592, 0.0, 127.3]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6], ['B', 'Jan', 136.861111111111, 4927, 0.0, 4926.999999999996, 627280.092592592, 0.0, 127.3], ['B', 'Feb', 77.2941176470588, 2628, 0.0, 2627.999999999999, 354264.7058823528, 0.0, 134.8]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6], ['B', 'Jan', 136.861111111111, 4927, 0.0, 4926.999999999996, 627280.092592592, 0.0, 127.3], ['B', 'Feb', 77.2941176470588, 2628, 0.0, 2627.999999999999, 354264.7058823528, 0.0, 134.8], ['B', 'Mar', 92.9375, 2974, 0.0, 2974.0, 425963.5416666666, 0.0, 143.2]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6], ['B', 'Jan', 136.861111111111, 4927, 0.0, 4926.999999999996, 627280.092592592, 0.0, 127.3], ['B', 'Feb', 77.2941176470588, 2628, 0.0, 2627.999999999999, 354264.7058823528, 0.0, 134.8], ['B', 'Mar', 92.9375, 2974, 0.0, 2974.0, 425963.5416666666, 0.0, 143.2], ['B', 'Apr', 68.7647058823529, 2338, 0.0, 2337.9999999999986, 315171.5686274508, 0.0, 134.8]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6], ['B', 'Jan', 136.861111111111, 4927, 0.0, 4926.999999999996, 627280.092592592, 0.0, 127.3], ['B', 'Feb', 77.2941176470588, 2628, 0.0, 2627.999999999999, 354264.7058823528, 0.0, 134.8], ['B', 'Mar', 92.9375, 2974, 0.0, 2974.0, 425963.5416666666, 0.0, 143.2], ['B', 'Apr', 68.7647058823529, 2338, 0.0, 2337.9999999999986, 315171.5686274508, 0.0, 134.8], ['B', 'May', 118.235294117647, 4020, 0.0, 4019.999999999998, 541911.7647058821, 0.0, 134.8]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6], ['B', 'Jan', 136.861111111111, 4927, 0.0, 4926.999999999996, 627280.092592592, 0.0, 127.3], ['B', 'Feb', 77.2941176470588, 2628, 0.0, 2627.999999999999, 354264.7058823528, 0.0, 134.8], ['B', 'Mar', 92.9375, 2974, 0.0, 2974.0, 425963.5416666666, 0.0, 143.2], ['B', 'Apr', 68.7647058823529, 2338, 0.0, 2337.9999999999986, 315171.5686274508, 0.0, 134.8], ['B', 'May', 118.235294117647, 4020, 0.0, 4019.999999999998, 541911.7647058821, 0.0, 134.8], ['B', 'Jun', 98.34375, 3147, 0.0, 3147.0, 450742.18749999994, 0.0, 143.2]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6], ['B', 'Jan', 136.861111111111, 4927, 0.0, 4926.999999999996, 627280.092592592, 0.0, 127.3], ['B', 'Feb', 77.2941176470588, 2628, 0.0, 2627.999999999999, 354264.7058823528, 0.0, 134.8], ['B', 'Mar', 92.9375, 2974, 0.0, 2974.0, 425963.5416666666, 0.0, 143.2], ['B', 'Apr', 68.7647058823529, 2338, 0.0, 2337.9999999999986, 315171.5686274508, 0.0, 134.8], ['B', 'May', 118.235294117647, 4020, 0.0, 4019.999999999998, 541911.7647058821, 0.0, 134.8], ['B', 'Jun', 98.34375, 3147, 0.0, 3147.0, 450742.18749999994, 0.0, 143.2], ['B', 'Jul', 85.4333333333333, 4271, 1708.0, 2562.9999999999986, 647769.4444444443, 40.0, 151.7]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6], ['B', 'Jan', 136.861111111111, 4927, 0.0, 4926.999999999996, 627280.092592592, 0.0, 127.3], ['B', 'Feb', 77.2941176470588, 2628, 0.0, 2627.999999999999, 354264.7058823528, 0.0, 134.8], ['B', 'Mar', 92.9375, 2974, 0.0, 2974.0, 425963.5416666666, 0.0, 143.2], ['B', 'Apr', 68.7647058823529, 2338, 0.0, 2337.9999999999986, 315171.5686274508, 0.0, 134.8], ['B', 'May', 118.235294117647, 4020, 0.0, 4019.999999999998, 541911.7647058821, 0.0, 134.8], ['B', 'Jun', 98.34375, 3147, 0.0, 3147.0, 450742.18749999994, 0.0, 143.2], ['B', 'Jul', 85.4333333333333, 4271, 1708.0, 2562.9999999999986, 647769.4444444443, 40.0, 151.7], ['B', 'Aug', 77.0588235294118, 2620, 0.0, 2620.0000000000014, 353186.27450980403, 0.0, 134.8]]
[['A', 'Jan', 145.555555555556, 5240, 0.0, 5240.000000000016, 727777.77777778, 0.0, 138.9], ['A', 'Feb', 143.470588235294, 4878, 0.0, 4877.999999999996, 717352.94117647, 0.0, 147.1], ['A', 'Mar', 185.6875, 5942, 0.0, 5942.0, 928437.5, 0.0, 156.2], ['A', 'Apr', 67.5588235294118, 2297, 0.0, 2297.0000000000014, 337794.11764705897, 0.0, 147.1], ['A', 'May', 58.5882352941176, 1992, 0.0, 1991.9999999999984, 292941.176470588, 0.0, 147.1], ['A', 'Jun', 71.09375, 2275, 0.0, 2275.0, 355468.75, 0.0, 156.2], ['A', 'Jul', 177.8, 5334, 0.0, 5334.0, 889000.0, 0.0, 166.7], ['A', 'Aug', 99.1470588235294, 3371, 0.0, 3370.9999999999995, 495735.29411764705, 0.0, 147.1], ['A', 'Sep', 104.416666666667, 3759, 0.0, 3759.000000000012, 522083.333333335, 0.0, 138.9], ['A', 'Oct', 110.28125, 3529, 0.0, 3529.0, 551406.25, 0.0, 156.2], ['A', 'Nov', 142.8, 4284, 0.0, 4284.0, 714000.0, 0.0, 166.7], ['A', 'Dec', 185.107142857143, 5183, 0.0, 5183.000000000004, 925535.714285715, 0.0, 178.6], ['B', 'Jan', 136.861111111111, 4927, 0.0, 4926.999999999996, 627280.092592592, 0.0, 127.3], ['B', 'Feb', 77.2941176470588, 2628, 0.0, 2627.999999999999, 354264.7058823528, 0.0, 134.8], ['B', 'Mar', 92.9375, 2974, 0.0, 2974.0, 425963.5416666666, 0.0, 143.2], ['B', 'Apr', 68.7647058823529, 2338, 0.0, 2337.9999999999986, 315171.5686274508, 0.0, 134.8], ['B', 'May', 118.235294117647, 4020, 0.0, 4019.999999999998, 541911.7647058821, 0.0, 134.8], ['B', 'Jun', 98.34375, 3147, 0.0, 3147.0, 450742.18749999994, 0.0, 143.2], ['B', 'Jul', 85.4333333333333, 4271, 1708.0, 2562.9999999999986, 647769.4444444443, 40.0, 151.7], ['B', 'Aug', 77.0588235294118, 2620, 0.0, 2620.0000000000014, 353186.27450980403, 0.0, 134.8], ['B', 'Sep', 125.472222222222, 4517, 0.0, 4516.999999999992, 575081.0185185175, 0.0, 127.3]]

In [47]:
# Creating dataframe for the results

Output_best = pd.DataFrame(Output_best, columns = ['State', 'Month', 'No of FTE Best',"Demand",
                                                   'No of Outsource App Best',"No of FTE Processed App Best", 
                                                   'Estimated Cost Best', 'Percent Outsourced App Best',  
                                                   'Average Cost Per Application Best'])


Output_best[['Estimated Cost in mn $ Best']] = Output_best[['Estimated Cost Best']]/1000000

Output_best['Demand'] = Output_best['Demand'].astype(int)

Output_best['No of Outsource App Best'] = Output_best['No of Outsource App Best'].astype(int)

Output_best['No of FTE Processed App Best'] = Output_best['No of FTE Processed App Best'].astype(int)

Output_best = Output_best.round({"No of FTE Best":1, "No of Outsource App Best":0, "Estimated Cost in mn $ Best":1})

In [48]:
#Various Parameters

total_outsourcing =  sum(Output_best['No of Outsource App Best'])

total_cost = sum(Output_best['Estimated Cost Best'])

optimal_staff_members = round(Output_best['No of FTE Best'].mean(),1)

total_demand =  sum(Output_best['Demand'])

average_cost_per_appln = round(total_cost/total_demand,2)

percent_outsourced_app_total = round((total_outsourcing/total_demand)*100,1)

print("Total Outsourced Application: ", total_outsourcing)

print("Total Demand Application: ", total_demand)

print("Optimal Staff Members : ", optimal_staff_members)

Total Outsourced Application:  4652
Total Demand Application:  113294
Optimal Staff Members :  92.9

#### 3.2.2 Percentage of outsourced applications

In [49]:
# write your code here

print("Total Outsourced Application % is : ", percent_outsourced_app_total)

Total Outsourced Application % is :  4.1

#### 3.2.3 Average cost per application

In [50]:
# write your code here

print("Average Cost per Application: ", average_cost_per_appln)

Average Cost per Application:  145.88

In [51]:
# Writing the results in to an Excel sheet

with pd.ExcelWriter('Output_Best_Q3.xlsx') as writer:
    Output_best.to_excel(writer)

# Question 4

#### Creating Visualisations

Create the following visualisations using your preferred method (i.e. Python, PowerPoint,Â Power BI, etc.) and add it to your report.Â 

Use the solution of Q2 to create a stacked column chart that shows the percentage of applications processed by the staff and by the vendor for each month (%staff processed applications+ %vendor processed applications should add up to 100%).Â 
Create a graph to show how the cost per application increases with respect to any change in the parameters in your analysis.
Hint: Use the cost per application that you calculate in Questions 2 and 3 (i.e., the best case, and the worst case).Â

**Note:** You can create the charts in Python or some other visualisation tools and make it a part of your final report directly.